version: "3.7"

services:
    # image project
    site:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        depends_on:
            - redis
        networks:
            - livewire

    # db postgres
    db:
        container_name: postgres-livewire
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
           - 5052:5432
        volumes:
           - ./.docker/pg-data:/var/lib/postgresql/data
        networks:
           - livewire

    # nginx web server
    nginx:
        container_name: nginx-livewire
        image: nginx
        restart: unless-stopped
        ports:
            - 8991:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - livewire
    # redis
    redis:
        container_name: redis-livewire
        image: redis:latest
        networks:
            - livewire


networks:
    livewire:
        driver: bridge
