version: "3.7"

services:
    # image project
    site:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        depends_on:
            - redis
        networks:
            - sinpges

    # db postgres
    db:
        container_name: postgres-livewire
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: sinpges
            POSTGRES_DB: sinpges
        ports:
           - "5052:5432"
        volumes:
           - ./.docker/pg-data:/var/lib/postgresql/data
        networks:
           - sinpges

    # nginx web server
    nginx:
        container_name: nginx-livewire
        image: nginx
        restart: unless-stopped
        ports:
            - 8991:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - sinpges
    # redis
    redis:
        container_name: redis-livewire
        image: redis:latest
        networks:
            - sinpges
    # adm db
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin-livewire
        ports:
            - 5050:80
        volumes:
            - ./.docker/pg-adm:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: sinpges@sinpges.com
            PGADMIN_DEFAULT_PASSWORD: sinpges
        networks:
            - sinpges

networks:
    sinpges:
        driver: bridge
